### ISSUE TITLE
Not Working with Double data type

### ISSUE THREAD

**Issue by mkrupal09** [Vram-Voskanyan/PrevGen#3]
here price is non null double data type and generated preview class generates double with null value

@DataPreview
data class Product(
    var id: String,
    var title: String,
    var description: String,
    var handle: String,
    var publishedAt: String,
    var createdAt: String,
    val price: Double ,
    var available: Boolean,
) {

**Generate class**

val productPreview = Product(
	id = "ryan_parker",
	title = "e3qtew",
	description = "u2iWJ3h",
	handle = "9RNNV",
	publishedAt = "hS5b2u4R",
	createdAt = "ZU3I",
	price = null,
	available = false,
)

**Comment by Vram-Voskanyan** [comment]
Hi @mkrupal09, thanks for using and reporting the issue. I'll take a look and come back to you soon.

**Comment by Vram-Voskanyan** [comment]
@mkrupal09 You were right, Double was not supported. I have added support and pushed the version (1.0.1). It will be available on MavenCentral within 30 minutes. If you find time, please update and ping me if everything is okay. Here's the PR.
https://github.com/Vram-Voskanyan/PrevGen/pull/4/files

**Comment by Vram-Voskanyan** [comment]
Off topic, I noticed in your Pojo file that some keys are generated as random strings. I added some logic for the 'title', 'description', 'created/published At' keys. Please update to version 1.0.2 and check it as well. ;)

**Comment by mkrupal09** [comment]
Thanks @Vram-Voskanyan for prompt reply and immediate fix
